services:
  backend-chat:
    image: ${DOCKER_REGISTRY:-buiyenit}/backendchat:${TAGS:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT:-Production} 
      - ASPNETCORE_URLS=https://+:80
      - SQLSERVER=${SQLSERVER:-sqlserver.default:1433}   
      - URL_MEET=${URL_MEET:-http://default-meet-url}
      - API_KEY_MEET=${API_KEY_MEET:-default-api-key}
      - LOG_LEVEL=${LOG_LEVEL:-Information}       
      - ASPNETCORE_Kestrel__Certificates__Default__Password=docker
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx 
    ports:
      - "9006:80"
    restart: always
    healthcheck:                                       
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:                                          
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:                                          
      - app-network
    volumes:                                       
      - ./logs:/app/logs
      - ./ssl:/https:rw

networks:
  app-network:
    driver: bridge